services:
    db:
        image: "postgres:13"
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_DB: rask
        ports:
            - "5000:5432"
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
    api:
        image: "jrheard/rask_api:latest"
        environment:
            DATABASE_URL: "postgres://postgres:password@db:5432/rask"
        ports:
            - "8001:8000"
        depends_on:
            - db