services:
    db:
        image: "postgres:13"
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_DB: rask
        ports:
            - "5000:5432"
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
