services:
    db:
        image: "postgres:13"
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_DB: rask
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
