networks:
    test:

services:
    db_test:
        image: "postgres:13"
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_DB: rask
        ports:
            - "5001:5432"
        networks:
            - test
    api_test:
        build:
            context: .
            dockerfile: Dockerfile.test
        environment:
            DATABASE_URL: "postgres://postgres:password@db:5432/rask"
            ROCKET_ADDRESS: "0.0.0.0"
        ports:
            - "8002:8000"
        depends_on:
            - db_test
        networks:
            - test