networks:
    default:

services:
    db:
        image: "postgres:13"
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_DB: rask
        ports:
            - "5000:5432"
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
        networks:
            - default
    api:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            DATABASE_URL: "postgres://postgres:password@db:5432/rask"
            ROCKET_ADDRESS: "0.0.0.0"
        ports:
            - "8001:8000"
        depends_on:
            - db
        networks:
            - default