GET http://127.0.0.1:8000/tasks/all

###
GET http://127.0.0.1:8000/tasks/alive

###
GET http://127.0.0.1:8000/task/1

###

GET http://127.0.0.1:8000/task/20

###

POST http://127.0.0.1:8000/task HTTP/1.1
Content-Type: application/x-www-form-urlencoded

name=foo&project=frank&due=2021-07-25%2023%3A56%3A04

###

POST http://127.0.0.1:8000/task/20/complete HTTP/1.1