GET http://127.0.0.1:8000/tasks

###
GET http://127.0.0.1:8000/task/1

###

GET http://127.0.0.1:8000/task/2

###

POST http://127.0.0.1:8000/task HTTP/1.1
content-type: application/json

{
    "name": "test task"
}
