name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Start Containers
      run: docker-compose -f "docker-compose-test.yaml" up -d
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: RUST_TESTING=1 cargo test --verbose
