on: [push]

name: Cargo tarpaulin

jobs:
  check:
    name: Cargo tarpaulin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-tarpaulin-${{ hashFiles('**/Cargo.lock') }}

      - name: Start containers
        run: docker-compose -f "docker-compose-test.yaml" up -d

      - name: Run cargo-tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        env:
          RUST_TESTING: 1
        with:
          args: '-v -- --test-threads 1'

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v2
