name: Cargo test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Cargo test

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Start containers
      run: docker-compose -f "docker-compose-test.yaml" up -d

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose -- --test-threads=1
      env:
        RUST_TESTING: 1
        RUST_BACKTRACE: 1
