name: Main

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Main

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Start containers
      run: docker-compose -f "docker-compose-test.yaml" up -d

    - name: Run tests
      run: cargo test --verbose -- --test-threads=1
      env:
        RUST_TESTING: 1
        RUST_BACKTRACE: 1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: jrheard/rask_api:latest
    -
      name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
