name: Main

on:
  push:
    branches: [ main ]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Start containers
        run: docker-compose -f "docker-compose-test.yaml" up -d

      - name: Run tests
        run: cargo test --verbose -- --test-threads=1
        env:
          RUST_TESTING: 1
          RUST_BACKTRACE: 1

  push:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Public ECR
        uses: docker/login-action@v1
        with:
          registry: public.ecr.aws
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: public.ecr.aws/q5h9o2a2/rask_api:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}